In [1]:
import pandas as pd
import numpy as np

In [22]:


# Original dataset
df1 = pd.read_csv(
    r"D:\internship-credibility-analyzer\data\fake_job_postings.csv\fake_job_postings.csv"
)

# Convert labels
# Original dataset:
# fraudulent = 1 => fake
# fraudulent = 0 => genuine
df1["label"] = 1 - df1["fraudulent"]

# Create unified text column
df1["posting_text"] = (
    df1["title"].fillna("") + " " +
    df1["company_profile"].fillna("") + " " +
    df1["description"].fillna("") + " " +
    df1["requirements"].fillna("") + " " +
    df1["benefits"].fillna("")
)

df1 = df1[["posting_text", "label"]]

# Indian internship dataset
df2 = pd.read_csv(
    r"D:\internship-credibility-analyzer\data\indian_internship_dataset_1000.csv"
)

df2 = df2[["posting_text", "label"]]

# Merge both datasets
df = pd.concat([df1, df2], ignore_index=True)

print(df.shape)
df.head()

(18880, 2)

                                        posting_text  label
0  Marketing Intern We're Food52, and we've creat...      1
1  Customer Service - Cloud Video Production 90 S...      1
2  Commissioning Machinery Assistant (CMA) Valor ...      1
3  Account Executive - Washington DC Our passion ...      1
4  Bill Review Manager SpotSource Solutions LLC i...      1

In [24]:
df.columns

Index(['posting_text', 'label'], dtype='object')

In [25]:
df["label"].value_counts() #0 = Legitimate Posting
#1 = Fraudulent Posting

label
1    17714
0     1166
Name: count, dtype: int64

In [26]:
df.isnull().sum()

posting_text    0
label           0
dtype: int64

In [27]:
list(df.columns)

['posting_text', 'label']

In [28]:
data = df.copy()

In [29]:
data["text"] = data["posting_text"]

In [30]:
data[["text", "label"]].head()

                                                text  label
0  Marketing Intern We're Food52, and we've creat...      1
1  Customer Service - Cloud Video Production 90 S...      1
2  Commissioning Machinery Assistant (CMA) Valor ...      1
3  Account Executive - Washington DC Our passion ...      1
4  Bill Review Manager SpotSource Solutions LLC i...      1

In [31]:
data[["text", "label"]].to_csv(r"D:\internship-credibility-analyzer\data\processed_data\cleaned_jobs.csv",
    index=False
)

In [32]:
data=pd.read_csv(r'D:\internship-credibility-analyzer\data\processed_data\cleaned_jobs.csv')

In [33]:
data

                                                    text  label
0      Marketing Intern We're Food52, and we've creat...      1
1      Customer Service - Cloud Video Production 90 S...      1
2      Commissioning Machinery Assistant (CMA) Valor ...      1
3      Account Executive - Washington DC Our passion ...      1
4      Bill Review Manager SpotSource Solutions LLC i...      1
...                                                  ...    ...
18875  Backend Development Internship at TCS in Benga...      1
18876  Machine Learning Internship at TCS in Pune. Mo...      1
18877  Urgent hiring for interns. Guaranteed income o...      0
18878  QA Testing Internship at CRED in Chennai. Mode...      1
18879  Full Stack Development Internship at Naukri in...      1

[18880 rows x 2 columns]

In [34]:
data.isnull().sum()

text     0
label    0
dtype: int64