In [1]:
import pandas as pd
df1 = pd.read_csv(
    r"D:\internship-credibility-analyzer\data\fake_job_postings.csv\fake_job_postings.csv"
)
df2 = pd.read_csv(
    r"D:\internship-credibility-analyzer\data\indian_internship_dataset_1000.csv"
)
df1["target"] = df1["fraudulent"]
df2["target"] = df2["label"]
df = pd.concat([df1, df2], ignore_index=True)

In [2]:
df.head()

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,...,target,posting_text,label,has_whatsapp_apply,has_registration_fee,has_company_email,has_duration_mentioned,has_no_interview,has_earn_daily,text_length
0,1.0,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0.0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0.0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0.0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0.0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0.0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
print(df.shape)
print(df.columns.tolist())
df.head()

(18880, 28)
['job_id', 'title', 'location', 'department', 'salary_range', 'company_profile', 'description', 'requirements', 'benefits', 'telecommuting', 'has_company_logo', 'has_questions', 'employment_type', 'required_experience', 'required_education', 'industry', 'function', 'fraudulent', 'target', 'posting_text', 'label', 'has_whatsapp_apply', 'has_registration_fee', 'has_company_email', 'has_duration_mentioned', 'has_no_interview', 'has_earn_daily', 'text_length']

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,...,target,posting_text,label,has_whatsapp_apply,has_registration_fee,has_company_email,has_duration_mentioned,has_no_interview,has_earn_daily,text_length
0,1.0,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0.0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0.0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0.0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0.0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0.0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#clean text
import re

In [5]:
def clean_text(text):
    
    text = str(text).lower()
    
    text = re.sub(r"http\S+", "", text)
    
    text = re.sub(r"www\S+", "", text)
    
    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text)
    
    text = re.sub(r"\s+", " ", text).strip()
    
    return text

In [6]:
df["text"] = df["posting_text"]
mask = df["text"].isna()

df.loc[mask, "text"] = (
    df.loc[mask, "title"].fillna("") + " " +
    df.loc[mask, "description"].fillna("") + " " +
    df.loc[mask, "requirements"].fillna("")
)

In [7]:
df["clean_text"] = df["text"].apply(clean_text)

In [8]:
print(df["clean_text"].str.split().str.len().describe())

count    18880.000000
mean       252.457256
std        166.660658
min          2.000000
25%        130.000000
50%        232.000000
75%        337.000000
max       2200.000000
Name: clean_text, dtype: float64

In [9]:
df["target"] = df["fraudulent"]
df["target"] = df["target"].fillna(df["label"])

In [10]:
print(df["target"].isna().sum())

0

In [11]:
X = df["clean_text"]
y = df["target"]

In [12]:
print(df["target"].value_counts())

target
0.0    17314
1.0     1566
Name: count, dtype: int64

In [13]:
print(df["fraudulent"].isna().sum())
print(df["label"].isna().sum())
print(len(df))

1000
17880
18880

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [17]:
vectorizer = TfidfVectorizer(
    max_features=10000,
    ngram_range=(1,2),
    min_df=2,
    stop_words="english"
)

In [18]:
feature_cols =[
    
        "has_whatsapp_apply",
        "has_registration_fee",
        "has_company_email",
        "has_duration_mentioned",
        "has_no_interview",
        "has_earn_daily",
        "text_length"
       
]
df[feature_cols] = df[feature_cols].fillna(0)
X_extra_train = df.loc[X_train.index, feature_cols]
X_extra_test = df.loc[X_test.index, feature_cols]

In [19]:
#transform
X_train_tfidf = vectorizer.fit_transform(X_train)

X_test_tfidf = vectorizer.transform(X_test)

In [20]:
from scipy.sparse import hstack

X_train_combined = hstack([
    X_train_tfidf,
    X_extra_train.values
])

X_test_combined = hstack([
    X_test_tfidf,
    X_extra_test.values
])

In [21]:
print(X_train_tfidf.shape)
print(X_train_combined.shape)
print(X_test_combined.shape)

(15104, 10000)
(15104, 10007)
(3776, 10007)

In [22]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    class_weight="balanced",
    max_iter=5000,
    random_state=42
)

model.fit(
    X_train_combined,
    y_train
)

y_pred = model.predict(
    X_test_combined
)

In [23]:
from sklearn.metrics import (
    accuracy_score,
    classification_report
)

In [24]:
print(
    accuracy_score(
        y_test,
        y_pred
    )
)

0.977489406779661

In [25]:
print(
    classification_report(
        y_test,
        y_pred
    )
)

              precision    recall  f1-score   support

         0.0       0.99      0.99      0.99      3463
         1.0       0.85      0.89      0.87       313

    accuracy                           0.98      3776
   macro avg       0.92      0.94      0.93      3776
weighted avg       0.98      0.98      0.98      3776

In [40]:
import joblib

joblib.dump(
    model,
    r"D:\internship-credibility-analyzer\models\fraud_detector.pkl"
)

joblib.dump(
    vectorizer,
    r"D:\internship-credibility-analyzer\models\tfidf_vectorizer.pkl"
)

print("Model saved successfully!")

Model saved successfully!

In [27]:
def count_exclamations(text):
    return text.count("!")

def text_length(text):
    return len(text)

def count_caps(text):
    return sum(1 for c in text if c.isupper())

In [28]:
urgency_words = [
    "urgent",
    "apply now",
    "limited",
    "immediately",
    "guaranteed",
    "fast hiring"
]

In [29]:
def urgency_count(text):
    text = text.lower()

    return sum(
        word in text
        for word in urgency_words
    )

In [30]:
df["exclamation_count"] = df["text"].apply(count_exclamations)

df["text_length"] = df["text"].apply(text_length)

df["caps_count"] = df["text"].apply(count_caps)

df["urgency_count"] = df["text"].apply(urgency_count)

In [31]:
df.groupby("target")[
[
"exclamation_count",
"text_length",
"caps_count",
"urgency_count"
]
].mean()

        exclamation_count  text_length  caps_count  urgency_count
target
0.0              0.390031  1818.862712   64.312406       0.199549
1.0              0.141124  1010.213921   46.067050       0.123244

In [32]:
df.groupby("fraudulent")[
[
    "exclamation_count",
    "text_length",
    "caps_count",
    "urgency_count"
]
].mean()

            exclamation_count  text_length  caps_count  urgency_count
fraudulent
0.0                  0.396908  1849.107206   65.361585       0.184671
1.0                  0.255196  1633.550808   71.116628       0.222864

In [33]:
import sklearn

print(sklearn.__version__)

1.9.0

In [34]:
def capital_ratio(text):
    text = str(text)

    total_letters = sum(c.isalpha() for c in text)

    if total_letters == 0:
        return 0

    capital_letters = sum(c.isupper() for c in text)

    return capital_letters / total_letters

In [35]:
df["capital_ratio"] = df["text"].apply(capital_ratio)

In [36]:
numerical_features = df[
    [
        "text_length",
        "has_whatsapp_apply",
        "has_registration_fee",
        "has_company_email",
        "has_duration_mentioned",
        "has_no_interview",
        "has_earn_daily"
    ]
]

In [37]:
numerical_features.head()

,text_length,has_whatsapp_apply,has_registration_fee,has_company_email,has_duration_mentioned,has_no_interview,has_earn_daily
0,1775,0.0,0.0,0.0,0.0,0.0,0.0
1,3553,0.0,0.0,0.0,0.0,0.0,0.0
2,1759,0.0,0.0,0.0,0.0,0.0,0.0
3,4064,0.0,0.0,0.0,0.0,0.0,0.0
4,2298,0.0,0.0,0.0,0.0,0.0,0.0

In [38]:
import os
import joblib

os.makedirs(r"D:\internship-credibility-analyzer\models", exist_ok=True)

joblib.dump(model, r"D:\internship-credibility-analyzer\models\fraud_detector.pkl")
joblib.dump(vectorizer, r"D:\internship-credibility-analyzer\models\tfidf_vectorizer.pkl")
joblib.dump(
    feature_cols,
    r"D:\internship-credibility-analyzer\models\feature_cols.pkl")
print("Saved successfully!")

Saved successfully!

In [39]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(
    y_test,
    y_pred
))

[[3412   51]
 [  34  279]]